# Generated by Django 3.0.4 on 2020-04-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Task',
        ),
    ]
