# Generated by Django 3.0.4 on 2020-04-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200412_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskList',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default='2020-04-12'),
        ),
    ]
